/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car2.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_1: THREE.Mesh
    Body_2: THREE.Mesh
    Body_3: THREE.Mesh
    Body_4: THREE.Mesh
    Body_5: THREE.Mesh
    Body_6: THREE.Mesh
    Body_7: THREE.Mesh
    Body_8: THREE.Mesh
    Body_9: THREE.Mesh
    Body_10: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Grills: THREE.MeshStandardMaterial
    Body_2: THREE.MeshStandardMaterial
    Window: THREE.MeshStandardMaterial
    Brakelights: THREE.MeshStandardMaterial
    Tailights: THREE.MeshStandardMaterial
    HeadLights: THREE.MeshStandardMaterial
    Bottom: THREE.MeshStandardMaterial
    ReverseLights: THREE.MeshStandardMaterial
    ['Number Plate']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.772, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Body_1.geometry} material={materials.Body} />
        <mesh geometry={nodes.Body_2.geometry} material={materials.Grills} />
        <mesh geometry={nodes.Body_3.geometry} material={materials.Body_2} />
        <mesh geometry={nodes.Body_4.geometry} material={materials.Window} />
        <mesh geometry={nodes.Body_5.geometry} material={materials.Brakelights} />
        <mesh geometry={nodes.Body_6.geometry} material={materials.Tailights} />
        <mesh geometry={nodes.Body_7.geometry} material={materials.HeadLights} />
        <mesh geometry={nodes.Body_8.geometry} material={materials.Bottom} />
        <mesh geometry={nodes.Body_9.geometry} material={materials.ReverseLights} />
        <mesh geometry={nodes.Body_10.geometry} material={materials['Number Plate']} />
      </group>
    </group>
  )
}

useGLTF.preload('/car2.glb')
