/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car_concept.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BodyUnderside: THREE.Mesh
    mesh_90: THREE.Mesh
    mesh_90_1: THREE.Mesh
    WheelFrontLBrakePad: THREE.Mesh
    WheelFrontLBrakeDisc: THREE.Mesh
    mesh_89: THREE.Mesh
    mesh_89_1: THREE.Mesh
    mesh_92: THREE.Mesh
    mesh_92_1: THREE.Mesh
    WheelFrontRBrakePad: THREE.Mesh
    WheelFrontRBrakeDisc: THREE.Mesh
    mesh_91: THREE.Mesh
    mesh_91_1: THREE.Mesh
    WheelRearLBrakeDisc: THREE.Mesh
    WheelRearLBrakePad: THREE.Mesh
    mesh_94: THREE.Mesh
    mesh_94_1: THREE.Mesh
    mesh_93: THREE.Mesh
    mesh_93_1: THREE.Mesh
    WheelRearRBrakeDisc: THREE.Mesh
    WheelRearRBrakePad: THREE.Mesh
    mesh_96: THREE.Mesh
    mesh_96_1: THREE.Mesh
    mesh_95: THREE.Mesh
    mesh_95_1: THREE.Mesh
    BodyWindshield: THREE.Mesh
    BodyWindshieldGasket: THREE.Mesh
    BodyWindshieldWipers: THREE.Mesh
    BodyWindshieldWipersBase: THREE.Mesh
    Engine: THREE.Mesh
    InteriorCage: THREE.Mesh
    InteriorDashMid: THREE.Mesh
    InteriorDashSides: THREE.Mesh
    InteriorFloor: THREE.Mesh
    InteriorFloormats: THREE.Mesh
    mesh_85: THREE.Mesh
    mesh_85_1: THREE.Mesh
    InteriorPedalAccel: THREE.Mesh
    InteriorPedalAccelArm: THREE.Mesh
    InteriorPedalBrake: THREE.Mesh
    InteriorPedalBrakeArm: THREE.Mesh
    InteriorPillar: THREE.Mesh
    InteriorSeatsColor1: THREE.Mesh
    InteriorSeatsColor2: THREE.Mesh
    InteriorSeatsFrame1: THREE.Mesh
    InteriorSeatsFrame2: THREE.Mesh
    InteriorSteeringBase: THREE.Mesh
    InteriorSteeringCylinder: THREE.Mesh
    InteriorSteeringEmblem: THREE.Mesh
    InteriorSteeringWheel04: THREE.Mesh
    InteriorSteeringWheel01: THREE.Mesh
    InteriorSteeringWheel02: THREE.Mesh
    InteriorSteeringWheel03: THREE.Mesh
    InteriorSteeringDash: THREE.Mesh
    InteriorSteeringDashColumn: THREE.Mesh
    InteriorSteeringHandleL: THREE.Mesh
    InteriorSteeringHandleR: THREE.Mesh
    License_Plate: THREE.Mesh
    BodyRoofPanel: THREE.Mesh
    BodyRearPanelsColor1: THREE.Mesh
    InteriorRearHatch: THREE.Mesh
    mesh_86: THREE.Mesh
    mesh_86_1: THREE.Mesh
    BodyWindowsRearSides: THREE.Mesh
    BodyTurnsignalsRear: THREE.Mesh
    BodyTaillightsPanels: THREE.Mesh
    BodyTaillights: THREE.Mesh
    BodyRearwindow: THREE.Mesh
    BodyPillars: THREE.Mesh
    BodyPanelsColor2: THREE.Mesh
    BodyHood: THREE.Mesh
    BodyHoodInterior01: THREE.Mesh
    BodyHoodInterior02: THREE.Mesh
    BodyHoodTopgrill: THREE.Mesh
    BodyHoodUnder: THREE.Mesh
    BodyHeadlights: THREE.Mesh
    BodyDoorRColor1: THREE.Mesh
    BodyDoorRColor2: THREE.Mesh
    BodyDoorRHandle01: THREE.Mesh
    BodyDoorRHandle02: THREE.Mesh
    BodyDoorRMirror: THREE.Mesh
    BodyDoorRMirrorColor1: THREE.Mesh
    BodyDoorRMirrorColor2: THREE.Mesh
    BodyDoorRWindow: THREE.Mesh
    BodyDoorRWindowGasket: THREE.Mesh
    mesh_87: THREE.Mesh
    mesh_87_1: THREE.Mesh
    InteriorDoorR02: THREE.Mesh
    InteriorDoorR03: THREE.Mesh
    InteriorDoorR04: THREE.Mesh
    InteriorDoorR05: THREE.Mesh
    InteriorDoorR06: THREE.Mesh
    BodyDoorLColor1: THREE.Mesh
    InteriorDoorL04: THREE.Mesh
    mesh_88: THREE.Mesh
    mesh_88_1: THREE.Mesh
    InteriorDoorL02: THREE.Mesh
    InteriorDoorL03: THREE.Mesh
    InteriorDoorL05: THREE.Mesh
    InteriorDoorL06: THREE.Mesh
    BodyDoorLColor2: THREE.Mesh
    BodyDoorLHandle01: THREE.Mesh
    BodyDoorLHandle02: THREE.Mesh
    BodyDoorLMirror: THREE.Mesh
    BodyDoorLMirrorColor1: THREE.Mesh
    BodyDoorLWindowGasket: THREE.Mesh
    BodyDoorLWindow: THREE.Mesh
    BodyDoorLMirrorColor2: THREE.Mesh
    Axles: THREE.Mesh
  }
  materials: {
    Mechanical: THREE.MeshStandardMaterial
    Rim2: THREE.MeshStandardMaterial
    Rim1: THREE.MeshStandardMaterial
    Brake: THREE.MeshStandardMaterial
    Disc: THREE.MeshStandardMaterial
    Tireside: THREE.MeshStandardMaterial
    Tiretread: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    ['Interior 1']: THREE.MeshStandardMaterial
    ['Interior 3 Carmine']: THREE.MeshStandardMaterial
    Floormat: THREE.MeshStandardMaterial
    ['Panel Sides']: THREE.MeshStandardMaterial
    Hardware: THREE.MeshStandardMaterial
    ['Interior 2']: THREE.MeshStandardMaterial
    Dashboard: THREE.MeshStandardMaterial
    License: THREE.MeshStandardMaterial
    ['Paint 2 Carmine']: THREE.MeshPhysicalMaterial
    ['Paint 1 Carmine']: THREE.MeshPhysicalMaterial
    Signallight: THREE.MeshStandardMaterial
    Brakelight: THREE.MeshStandardMaterial
    Headlight: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car_concept.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BodyUnderside.geometry} material={materials.Mechanical} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.975, -1.486, 0.384]} rotation={[2.159, -0.448, 0.281]}>
          <group position={[-0.001, 0, 0]}>
            <mesh geometry={nodes.mesh_90.geometry} material={materials.Rim2} />
            <mesh geometry={nodes.mesh_90_1.geometry} material={materials.Rim1} />
          </group>
          <mesh geometry={nodes.WheelFrontLBrakePad.geometry} material={materials.Brake} position={[-0.001, 0, 0]} />
          <mesh geometry={nodes.WheelFrontLBrakeDisc.geometry} material={materials.Disc} position={[-0.001, 0, 0]} />
          <mesh geometry={nodes.mesh_89.geometry} material={materials.Tireside} />
          <mesh geometry={nodes.mesh_89_1.geometry} material={materials.Tiretread} />
        </group>
        <group position={[-0.977, -1.484, 0.384]} rotation={[0.714, -0.361, -0.388]}>
          <group position={[0, -0.001, 0]}>
            <mesh geometry={nodes.mesh_92.geometry} material={materials.Rim2} />
            <mesh geometry={nodes.mesh_92_1.geometry} material={materials.Rim1} />
          </group>
          <mesh geometry={nodes.WheelFrontRBrakePad.geometry} material={materials.Brake} position={[0, -0.001, 0]} />
          <mesh geometry={nodes.WheelFrontRBrakeDisc.geometry} material={materials.Disc} position={[0, -0.001, 0]} />
          <mesh geometry={nodes.mesh_91.geometry} material={materials.Tireside} />
          <mesh geometry={nodes.mesh_91_1.geometry} material={materials.Tiretread} />
        </group>
        <group position={[0.983, 1.314, 0.384]} rotation={[-1.92, 0, 0]}>
          <mesh geometry={nodes.WheelRearLBrakeDisc.geometry} material={materials.Disc} />
          <mesh geometry={nodes.WheelRearLBrakePad.geometry} material={materials.Brake} />
          <mesh geometry={nodes.mesh_94.geometry} material={materials.Rim2} />
          <mesh geometry={nodes.mesh_94_1.geometry} material={materials.Rim1} />
          <mesh geometry={nodes.mesh_93.geometry} material={materials.Tireside} />
          <mesh geometry={nodes.mesh_93_1.geometry} material={materials.Tiretread} />
        </group>
        <group position={[-0.982, 1.314, 0.384]} rotation={[-0.96, 0, 0]}>
          <mesh geometry={nodes.WheelRearRBrakeDisc.geometry} material={materials.Disc} position={[-0.001, 0, 0]} />
          <mesh geometry={nodes.WheelRearRBrakePad.geometry} material={materials.Brake} position={[-0.001, 0, 0]} />
          <group position={[-0.001, 0, 0]}>
            <mesh geometry={nodes.mesh_96.geometry} material={materials.Rim2} />
            <mesh geometry={nodes.mesh_96_1.geometry} material={materials.Rim1} />
          </group>
          <mesh geometry={nodes.mesh_95.geometry} material={materials.Tireside} />
          <mesh geometry={nodes.mesh_95_1.geometry} material={materials.Tiretread} />
        </group>
        <mesh geometry={nodes.BodyWindshield.geometry} material={materials.Glass} />
        <mesh geometry={nodes.BodyWindshieldGasket.geometry} material={nodes.BodyWindshieldGasket.material} />
        <mesh geometry={nodes.BodyWindshieldWipers.geometry} material={nodes.BodyWindshieldWipers.material} position={[0.682, -1.427, 0.849]} />
        <mesh geometry={nodes.BodyWindshieldWipersBase.geometry} material={nodes.BodyWindshieldWipersBase.material} />
        <mesh geometry={nodes.Engine.geometry} material={materials.Mechanical} position={[0, -2.076, 0.14]} />
        <mesh geometry={nodes.InteriorCage.geometry} material={nodes.InteriorCage.material} />
        <mesh geometry={nodes.InteriorDashMid.geometry} material={materials['Interior 1']} />
        <mesh geometry={nodes.InteriorDashSides.geometry} material={materials['Interior 3 Carmine']} />
        <mesh geometry={nodes.InteriorFloor.geometry} material={nodes.InteriorFloor.material} />
        <mesh geometry={nodes.InteriorFloormats.geometry} material={materials.Floormat} />
        <mesh geometry={nodes.InteriorPedalAccel.geometry} material={materials.Floormat} position={[-0.075, -1.459, 0.129]} />
        <mesh geometry={nodes.InteriorPedalAccelArm.geometry} material={materials.Hardware} position={[-0.076, -1.459, 0.129]} />
        <mesh geometry={nodes.InteriorPedalBrake.geometry} material={materials.Floormat} position={[0.076, -1.523, 0.21]} />
        <mesh geometry={nodes.InteriorPedalBrakeArm.geometry} material={materials.Hardware} position={[0.076, -1.427, 0.129]} />
        <mesh geometry={nodes.InteriorPillar.geometry} material={nodes.InteriorPillar.material} />
        <mesh geometry={nodes.InteriorSeatsColor1.geometry} material={materials['Interior 3 Carmine']} position={[0.509, -0.133, -0.16]} />
        <mesh geometry={nodes.InteriorSeatsColor2.geometry} material={materials['Interior 2']} position={[0, -0.805, -0.193]} />
        <mesh geometry={nodes.InteriorSeatsFrame1.geometry} material={nodes.InteriorSeatsFrame1.material} position={[0, 0.606, -0.18]} />
        <mesh geometry={nodes.InteriorSeatsFrame2.geometry} material={nodes.InteriorSeatsFrame2.material} position={[0, -0.805, -0.193]} />
        <mesh geometry={nodes.InteriorSteeringBase.geometry} material={nodes.InteriorSteeringBase.material} position={[0, -0.929, 0.642]} />
        <mesh geometry={nodes.InteriorSteeringCylinder.geometry} material={nodes.InteriorSteeringCylinder.material} position={[0.001, -1.163, 0.551]} rotation={[0.378, -0.262, 0]}>
          <mesh geometry={nodes.InteriorSteeringEmblem.geometry} material={materials.Hardware} position={[0, 0.25, -0.002]} rotation={[-0.378, 0, 0]} />
          <mesh geometry={nodes.InteriorSteeringWheel04.geometry} material={nodes.InteriorSteeringWheel04.material} position={[0, 0.197, -0.001]} rotation={[-0.378, 0, 0]} />
          <mesh geometry={nodes.InteriorSteeringWheel01.geometry} material={materials['Interior 3 Carmine']} position={[0, 0.25, -0.002]} rotation={[-0.378, 0, 0]} />
          <mesh geometry={nodes.InteriorSteeringWheel02.geometry} material={materials['Interior 1']} position={[0, 0.25, -0.002]} rotation={[-0.378, 0, 0]} />
          <mesh geometry={nodes.InteriorSteeringWheel03.geometry} material={materials['Interior 1']} position={[0, 0.25, -0.002]} rotation={[-0.378, 0, 0]} />
        </mesh>
        <mesh geometry={nodes.InteriorSteeringDash.geometry} material={materials.Dashboard} position={[-0.006, -1.022, 0.613]} />
        <mesh geometry={nodes.InteriorSteeringDashColumn.geometry} material={nodes.InteriorSteeringDashColumn.material} position={[-0.006, -1.022, 0.613]} />
        <mesh geometry={nodes.InteriorSteeringHandleL.geometry} material={materials.Hardware} position={[0.072, -1.2, 0.53]} />
        <mesh geometry={nodes.InteriorSteeringHandleR.geometry} material={materials.Hardware} position={[-0.07, -1.2, 0.53]} />
        <mesh geometry={nodes.License_Plate.geometry} material={materials.License} position={[0, 1.885, 0.255]} />
        <mesh geometry={nodes.BodyRoofPanel.geometry} material={materials['Paint 2 Carmine']} />
        <mesh geometry={nodes.BodyRearPanelsColor1.geometry} material={materials['Paint 1 Carmine']} position={[0, 1.929, 0.423]}>
          <mesh geometry={nodes.InteriorRearHatch.geometry} material={nodes.InteriorRearHatch.material} position={[0, -1.927, -0.43]} />
          <group position={[0, -1.927, -0.43]}>
            <mesh geometry={nodes.mesh_86.geometry} material={materials.Mechanical} />
            <mesh geometry={nodes.mesh_86_1.geometry} material={materials['Interior 1']} />
          </group>
          <mesh geometry={nodes.BodyWindowsRearSides.geometry} material={materials.Glass} position={[0, -1.927, -0.43]} />
          <mesh geometry={nodes.BodyTurnsignalsRear.geometry} material={materials.Signallight} position={[0, -1.927, -0.43]} />
          <mesh geometry={nodes.BodyTaillightsPanels.geometry} material={nodes.BodyTaillightsPanels.material} position={[0, -1.927, -0.43]} />
          <mesh geometry={nodes.BodyTaillights.geometry} material={materials.Brakelight} position={[0, -1.927, -0.43]} />
          <mesh geometry={nodes.BodyRearwindow.geometry} material={materials.Glass} position={[0, -1.927, -0.43]} />
        </mesh>
        <mesh geometry={nodes.BodyPillars.geometry} material={materials['Paint 1 Carmine']} />
        <mesh geometry={nodes.BodyPanelsColor2.geometry} material={materials['Paint 2 Carmine']} />
        <mesh geometry={nodes.BodyHood.geometry} material={materials['Paint 1 Carmine']} position={[0, -2.379, 0.176]}>
          <mesh geometry={nodes.BodyHoodInterior01.geometry} material={nodes.BodyHoodInterior01.material} position={[0, 2.378, -0.188]} />
          <mesh geometry={nodes.BodyHoodInterior02.geometry} material={nodes.BodyHoodInterior02.material} position={[0, 2.378, -0.188]} />
          <mesh geometry={nodes.BodyHoodTopgrill.geometry} material={materials['Paint 2 Carmine']} position={[0, 2.378, -0.188]} />
          <mesh geometry={nodes.BodyHoodUnder.geometry} material={nodes.BodyHoodUnder.material} position={[0, 2.378, -0.188]} />
          <mesh geometry={nodes.BodyHeadlights.geometry} material={materials.Headlight} position={[0, 2.378, -0.188]} />
        </mesh>
        <mesh geometry={nodes.BodyDoorRColor1.geometry} material={materials['Paint 1 Carmine']} position={[-1.087, -0.998, 0.643]}>
          <mesh geometry={nodes.BodyDoorRColor2.geometry} material={materials['Paint 2 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRHandle01.geometry} material={nodes.BodyDoorRHandle01.material} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRHandle02.geometry} material={materials['Paint 2 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRMirror.geometry} material={materials.Mirror} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRMirrorColor1.geometry} material={materials['Paint 1 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRMirrorColor2.geometry} material={materials['Paint 2 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRWindow.geometry} material={materials.Glass} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorRWindowGasket.geometry} material={nodes.BodyDoorRWindowGasket.material} position={[1.091, 0.994, -0.643]} />
          <group position={[1.091, 0.994, -0.643]}>
            <mesh geometry={nodes.mesh_87.geometry} material={materials.Mechanical} />
            <mesh geometry={nodes.mesh_87_1.geometry} material={materials['Interior 1']} />
          </group>
          <mesh geometry={nodes.InteriorDoorR02.geometry} material={materials['Interior 1']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorR03.geometry} material={materials['Interior 3 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorR04.geometry} material={materials['Interior 3 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorR05.geometry} material={materials['Interior 3 Carmine']} position={[1.091, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorR06.geometry} material={materials.Hardware} position={[1.091, 0.994, -0.643]} />
        </mesh>
        <mesh geometry={nodes.BodyDoorLColor1.geometry} material={materials['Paint 1 Carmine']} position={[1.089, -0.998, 0.643]}>
          <mesh geometry={nodes.InteriorDoorL04.geometry} material={materials['Interior 3 Carmine']} position={[-1.092, 0.994, -0.643]} />
          <group position={[-1.092, 0.994, -0.643]}>
            <mesh geometry={nodes.mesh_88.geometry} material={materials.Mechanical} />
            <mesh geometry={nodes.mesh_88_1.geometry} material={materials['Interior 1']} />
          </group>
          <mesh geometry={nodes.InteriorDoorL02.geometry} material={materials['Interior 1']} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorL03.geometry} material={materials['Interior 3 Carmine']} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorL05.geometry} material={materials['Interior 3 Carmine']} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.InteriorDoorL06.geometry} material={materials.Hardware} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLColor2.geometry} material={materials['Paint 2 Carmine']} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLHandle01.geometry} material={nodes.BodyDoorLHandle01.material} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLHandle02.geometry} material={materials['Paint 2 Carmine']} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLMirror.geometry} material={materials.Mirror} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLMirrorColor1.geometry} material={materials['Paint 1 Carmine']} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLWindowGasket.geometry} material={nodes.BodyDoorLWindowGasket.material} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLWindow.geometry} material={materials.Glass} position={[-1.092, 0.994, -0.643]} />
          <mesh geometry={nodes.BodyDoorLMirrorColor2.geometry} material={materials['Paint 2 Carmine']} position={[-1.092, 0.994, -0.643]} />
        </mesh>
        <mesh geometry={nodes.Axles.geometry} material={materials.Mechanical} position={[0, -0.091, 0.384]} />
        <mesh geometry={nodes.mesh_85.geometry} material={materials['Panel Sides']} />
        <mesh geometry={nodes.mesh_85_1.geometry} material={materials['Panel Sides']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/car_concept.glb')
